<a href="https://colab.research.google.com/github/narie-monarie/numpypandas/blob/main/numpy01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import numpy as np

In [ ]:
sales = [[3,5,4,23,3],[20,43,56,12,76]]
sales_array = np.array(sales)

In [ ]:
print(f"shape: {sales_array.shape}")
print(f"dtype: {sales_array.dtype}")
print(f"ndim: {sales_array.ndim}")
print(f"size: {sales_array.size}")

shape: (2, 5)
dtype: int64
ndim: 2
size: 10


In [ ]:
array_2d = np.array([range(100),range(100)])
array_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
        80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
        80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [ ]:
print(f"shape: {array_2d.shape}")
print(f"dtype: {array_2d.dtype}")
print(f"ndim: {array_2d.ndim}")
print(f"size: {array_2d.size}")

shape: (2, 100)
dtype: int64
ndim: 2
size: 200


In [ ]:
my_list = [x * 10 for x in range(1, 11)]
my_list_arr = np.array(my_list)
my_list_arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
my_list_arr.ndim

1

In [ ]:
my_list_arr.shape

(10,)

In [ ]:
my_list_arr.size

10

In [ ]:
my_list_arr.dtype

dtype('int64')

In [ ]:
array = [
    [1,2,3],
    [7,5,4],
    [9,11,56]
]
arrayx = np.array(array)

In [ ]:
# The First 2 rows
arrayx[:2,:]

array([[1, 2, 3],
       [7, 5, 4]])

In [ ]:
arrayx[:,:1]

array([[1],
       [7],
       [9]])

In [ ]:
arrayx[2, 1]

11

In [ ]:
sales_array + 2

array([[ 5,  7,  6, 25,  5],
       [22, 45, 58, 14, 78]])

In [ ]:
quantity = sales_array[0,:]
price = sales_array[1,:]

In [ ]:
quantity * price

array([ 60, 215, 224, 276, 228])

In [ ]:
price = np.array([5.99,6.99,22.49,99.99,4.99,49.99])

In [ ]:
total_p = price + 5
total_p

array([ 10.99,  11.99,  27.49, 104.99,   9.99,  54.99])

In [ ]:
sales_array != np.where(inv_arr <= 0, "Out of Stock", "In stock")0

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [ ]:
z = np.random.rand(1,6)
print(z)

[[0.39498942 0.12087175 0.31772469 0.93828811 0.46049488 0.55124933]]


In [ ]:
price_disc = z[:1].reshape(6)
disc = 1 - price_disc
disc

array([0.60501058, 0.87912825, 0.68227531, 0.06171189, 0.53950512,
       0.44875067])

In [ ]:
total = total_p * disc
total.round(2)

array([ 6.65, 10.54, 18.76,  6.48,  5.39, 24.68])

In [ ]:
# Filtering Arrays

In [ ]:
sales_array != 0

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [ ]:
sales_array[sales_array != 9]

array([ 3,  5,  4, 23,  3, 20, 43, 56, 12, 76])

In [ ]:
sales_array[(sales_array == 3) | (sales_array > 5)]

array([ 3, 23,  3, 20, 43, 56, 12, 76])

In [ ]:
mask = (sales_array > 6) & (sales_array < 20)
sales_array[mask]

array([12])

## **Where** Function

In [ ]:
prod = np.array(
    ['fruits','vegetables','cereal', 'dairy', 'eggs']
    )

In [ ]:
inv_arr = np.array([1,102,7,0,0])

In [ ]:
np.where(inv_arr <= 0, "Out of Stock", "In stock")
np.where(inv_arr <= 0, "Out of Stock", inv_arr)

array(['12', '102', '18', 'Out of Stock', 'Out of Stock'], dtype='<U21')

In [ ]:
np.where(inv_arr % 2 == 0, "even", np.where(inv_arr == 7, inv_arr, "naah"))

array(['naah', 'even', '7', 'even', 'even'], dtype='<U21')

In [114]:
#sum
#mean
#man
#min

In [115]:
sales_array.sum(axis=0)

array([23, 48, 60, 35, 79])

In [116]:

sales_array.sum(axis=1)

array([ 38, 207])

In [117]:
sales_array

array([[ 3,  5,  4, 23,  3],
       [20, 43, 56, 12, 76]])

In [118]:
np.median(sales_array)

16.0